name: movie_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_bloc: ^8.0.1
  icon_shadow: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/mvg.png
  #   - images/a_dot_ham.jpeg

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: RubikMarkerHatch
      fonts:
        - asset: fonts/RubikMarkerHatch-Regular.ttf

    - family: SecularOne
      fonts:
        - asset: fonts/SecularOne-Regular.ttf

  # see https://flutter.dev/custom-fonts/#from-packages
